### ISSUE TITLE
TODO - List Emotes & Expressions

### ISSUE THREAD

**Issue by axtonprice** [axtonprice/axtons-emotes#1]
- [x] Complete list emotes and expressions command. `/emotes` , `/expressions`
  - [x] Call validation methods
  - [x] Create object of relevant commands with command details
  - [x] Loop through object in output message with color formatting

Commands have already been added and registered in [v1.2 release](https://github.com/axtonprice/axtons-emotes/releases/tag/v1.2). 
Execution of command temporarily returns "Coming Soon" until proper execution implementation is finished.
