### ISSUE TITLE
TODO - Automatic configuration migration

### ISSUE THREAD

**Issue by axtonprice** [axtonprice/axtons-emotes#3]
Implement an automatic configuration file migration system that detects and adds new configuration keys when users upgrade to newer releases. The system should ensure that existing configuration keys remain intact, only inserting keys that are missing in the older configuration files.

- [ ] Add method - Fetch the latest configuration layout from the GitHub source repository.
- [ ] Add method - Loop through each key of the Github configuration, and compare it against the plugin's configuration until one of the keys is not present.
- [ ] Add method - Insert new configuration key from GitHub to plugin configuration.
- [ ] Add error handling - Ensure GitHub.com is reachable and debug log if not.
